/**
 * Centralized Role-Based Access Control (RBAC) Constants
 * Used for platform administration and multi-tenant organization management.
 */

const ROLES = {
  OWNER: "OWNER",
  ADMIN: "ADMIN",
  MANAGER: "MANAGER",
  TEAM_LEAD: "TEAM_LEAD",
  EMPLOYEE: "EMPLOYEE",
  SUPPORT_AGENT: "SUPPORT_AGENT",
  CUSTOMER: "CUSTOMER",
};

const ROLE_HIERARCHY = {
  [ROLES.OWNER]: 100,
  [ROLES.ADMIN]: 80,
  [ROLES.MANAGER]: 60,
  [ROLES.TEAM_LEAD]: 40,
  [ROLES.SUPPORT_AGENT]: 30,
  [ROLES.EMPLOYEE]: 20,
  [ROLES.CUSTOMER]: 10,
};

const PERMISSIONS = {
  // Organization management
  ORG_MANAGE: "org:manage",
  ORG_VIEW: "org:view",
  ORG_DELETE: "org:delete",
  
  // Team management
  TEAM_MANAGE: "team:manage",
  TEAM_VIEW: "team:view",

  // Member & Role management
  MEMBER_INVITE: "member:invite",
  MEMBER_MANAGE_ROLE: "member:manage_role",
  MEMBER_REMOVE: "member:remove",

  // Business Chat & Support Inbox
  INBOX_VIEW_ALL: "inbox:view_all",
  INBOX_ASSIGN: "inbox:assign",
  INBOX_RESOLVE: "inbox:resolve",
  INBOX_INTERNAL_NOTES: "inbox:internal_notes",
  INBOX_TRANSFER: "inbox:transfer",

  // Knowledge Base & RAG
  KB_UPLOAD: "kb:upload",
  KB_DELETE: "kb:delete",
  KB_QUERY: "kb:query",

  // Analytics & AI
  ANALYTICS_VIEW: "analytics:view",
  AI_ADVANCED: "ai:advanced",
  AI_USAGE_VIEW: "ai:usage_view",

  // Audit Logs
  AUDIT_LOG_VIEW: "audit:view",
};

const ROLE_PERMISSIONS = {
  [ROLES.OWNER]: Object.values(PERMISSIONS),
  [ROLES.ADMIN]: [
    PERMISSIONS.ORG_VIEW,
    PERMISSIONS.ORG_MANAGE,
    PERMISSIONS.TEAM_MANAGE,
    PERMISSIONS.TEAM_VIEW,
    PERMISSIONS.MEMBER_INVITE,
    PERMISSIONS.MEMBER_MANAGE_ROLE,
    PERMISSIONS.MEMBER_REMOVE,
    PERMISSIONS.INBOX_VIEW_ALL,
    PERMISSIONS.INBOX_ASSIGN,
    PERMISSIONS.INBOX_RESOLVE,
    PERMISSIONS.INBOX_INTERNAL_NOTES,
    PERMISSIONS.INBOX_TRANSFER,
    PERMISSIONS.KB_UPLOAD,
    PERMISSIONS.KB_DELETE,
    PERMISSIONS.KB_QUERY,
    PERMISSIONS.ANALYTICS_VIEW,
    PERMISSIONS.AI_ADVANCED,
    PERMISSIONS.AI_USAGE_VIEW,
    PERMISSIONS.AUDIT_LOG_VIEW,
  ],
  [ROLES.MANAGER]: [
    PERMISSIONS.ORG_VIEW,
    PERMISSIONS.TEAM_MANAGE,
    PERMISSIONS.TEAM_VIEW,
    PERMISSIONS.MEMBER_INVITE,
    PERMISSIONS.INBOX_VIEW_ALL,
    PERMISSIONS.INBOX_ASSIGN,
    PERMISSIONS.INBOX_RESOLVE,
    PERMISSIONS.INBOX_INTERNAL_NOTES,
    PERMISSIONS.INBOX_TRANSFER,
    PERMISSIONS.KB_UPLOAD,
    PERMISSIONS.KB_QUERY,
    PERMISSIONS.ANALYTICS_VIEW,
    PERMISSIONS.AI_ADVANCED,
  ],
  [ROLES.TEAM_LEAD]: [
    PERMISSIONS.ORG_VIEW,
    PERMISSIONS.TEAM_VIEW,
    PERMISSIONS.INBOX_VIEW_ALL,
    PERMISSIONS.INBOX_ASSIGN,
    PERMISSIONS.INBOX_RESOLVE,
    PERMISSIONS.INBOX_INTERNAL_NOTES,
    PERMISSIONS.INBOX_TRANSFER,
    PERMISSIONS.KB_QUERY,
    PERMISSIONS.ANALYTICS_VIEW,
  ],
  [ROLES.SUPPORT_AGENT]: [
    PERMISSIONS.ORG_VIEW,
    PERMISSIONS.TEAM_VIEW,
    PERMISSIONS.INBOX_VIEW_ALL,
    PERMISSIONS.INBOX_ASSIGN,
    PERMISSIONS.INBOX_RESOLVE,
    PERMISSIONS.INBOX_INTERNAL_NOTES,
    PERMISSIONS.INBOX_TRANSFER,
    PERMISSIONS.KB_QUERY,
  ],
  [ROLES.EMPLOYEE]: [
    PERMISSIONS.ORG_VIEW,
    PERMISSIONS.TEAM_VIEW,
    PERMISSIONS.KB_QUERY,
  ],
  [ROLES.CUSTOMER]: [
    PERMISSIONS.KB_QUERY,
  ],
};

module.exports = {
  ROLES,
  ROLE_HIERARCHY,
  PERMISSIONS,
  ROLE_PERMISSIONS,
};
